name: Upload Python Package to PyPI

on:
  push:
    branches:
      - dev

  release:
    branches:
      - master
    types: [published]

  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Update Pip
        run: python -m pip install --upgrade pip
      
      - name: Install Python dependencies
        run: python -m pip install --upgrade --no-cache-dir build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI or PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_PASSWORD_TEST: ${{ secrets.PYPI_TEST_API_TOKEN }}
        run: |
          if [ "$GITHUB_EVENT_NAME" = "release" ]; then
            echo "Publishing to PyPI..."
            twine upload dist/* \
              -u __token__ \
              -p "${TWINE_PASSWORD}"
          else
            echo "Publishing to TestPyPI..."
            twine upload dist/* \
              --repository testpypi \
              -u __token__ \
              -p "${TWINE_PASSWORD_TEST}"
          fi